export const products = [
  //PS4
  {
    id: 1,
    title: "Dark Souls REMASTER",
    price: 39.99,
    stock: 5,
    category: "Action RPG",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686519/React/DS1_slxuqz.png",
  },
  {
    id: 2,
    title: "Dark Souls 2 - SoFS",
    price: 39.99,
    stock: 5,
    category: "Action RPG",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686520/React/DS2_hgw1nc.png",
  },
  {
    id: 3,
    title: "Dark Souls 3",
    price: 59.99,
    stock: 5,
    category: "Action RPG",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686521/React/DS3_yogfzq.png",
  },
  {
    id: 4,
    title: "BloodBorne - GOTY Edition",
    price: 34.99,
    category: "Action RPG",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686518/React/BB_ta0fwh.png",
  },
  {
    id: 5,
    title: "Sekiro - Shadows Die Twice",
    price: 59.99,
    stock: 5,
    category: "Action RPG",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686518/React/Sekiro_mrtmmm.png",
  },
  //PS5
  {
    id: 6,
    title: "Demon Souls",
    price: 69.99,
    stock: 5,
    category: "Action RPG",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686520/React/DS_elffbg.png",
  },
  {
    id: 7,
    title: "ELDEN RING",
    price: 59.99,
    stock: 5,
    category: "Action RPG",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686518/React/ER_quhwuj.png",
  },
  {
    id: 8,
    title: "Horizon - Forbidden West",
    price: 59.99,
    stock: 5,
    category: "Open World",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686519/React/HOR_tcqdx1.png",
  },
  {
    id: 9,
    title: "Death Stranding",
    price: 49.99,
    stock: 5,
    category: "Open World",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686519/React/DSTRA_ddlrcl.png",
  },
  {
    id: 10,
    title: "Little Nightmares",
    price: 19.99,
    stock: 5,
    category: "Horror",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1681614943/littlen_foujm6.png",
  },
  //Software
  {
    id: 11,
    title: "Windows 10 Home",
    price: 19.99,
    stock: 5,
    category: "OS",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686519/React/w10_vnndef.png",
  },
  {
    id: 12,
    title: "Windows 11 Pro",
    price: 19.99,
    stock: 5,
    category: "OS",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686520/React/w11_dvhedl.png",
  },
  {
    id: 13,
    title: "Microsoft Office 365 Proplus",
    price: 14.99,
    stock: 5,
    category: "Service",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686518/React/MO_parbfe.png",
  },
  {
    id: 14,
    title: "Adobe Photoshop 2023",
    price: 14.99,
    stock: 5,
    category: "Service",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686518/React/PS_jmr08n.png",
  },
  {
    id: 15,
    title: "Adobe Premiere 2023",
    price: 14.99,
    stock: 5,
    category: "Service",
    img: "https://res.cloudinary.com/drpr8hciz/image/upload/v1680686519/React/AP_yg7c2i.png",
  },
];
